crowdFunding/crowdFunding/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings
from projects import urls, views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/' , include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('projects/',include('projects.urls')),
    path('search/',views.search),
    path('',views.home, name = 'home'),
    path('categories/', include('categories.urls')),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crowdFunding/projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('projectDetails/<int:id>',views.showProject,name="show_proj"),
    path('showCategory/<int:id>',views.showCategoryProjects ,name="show_cate"),
    path('<int:id>/comment', views.create_comment, name = 'create_comment'),
    path('<int:id>/report_pro', views.report_project, name = 'report_project'),
    path('<int:id>/report_com', views.report_comment, name = 'report_comment'),
    path('<int:id>/donate', views.donate, name = 'donate'),
    path('create', views.create,name='create_project'),
    path('tags/<slug:slug>', views.show_tag,name='show_tag'),
    path('<int:id>/rate/<int:value>', views.rate_project, name='rate_project'),
    path('<int:id>/delete', views.delete_project, name='delete_project'),
    path('search', views.search, name='search')]

crowdFunding/users/urls.py
# from django.conf.urls import url
from django.urls import path , include , re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('profile/<int:uid>', views.userProfile , name='profile'),

    path('edit/<int:uid>', views.editProfile , name='edit'),
    path('delete/<int:uid>', views.deleteuser, name="delete"),
    path('signup',views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view\
        (template_name='users/logout.html'), name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    
    # path('login/', views.custom_login),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate_account, name='activate')

]

crowdFunding/projects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from datetime import datetime
from users.models import Profile
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager
from django.core.validators import MaxValueValidator, MinValueValidator

class Project(models.Model):
    title = models.CharField(max_length=45)
    details = models.TextField(max_length=3000)
    target = models.IntegerField()
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    is_featured = models.BooleanField(default=False)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)
    tags = TaggableManager()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return str(self.title)


class Category(models.Model):
    name = models.CharField(max_length=45)
    cat_icon = models.ImageField(upload_to='static/imgs/', default=True)

    def __str__(self):
        return str(self.name)


class ProjectPicture(models.Model):
    img_url = models.ImageField(upload_to='static/imgs/', verbose_name='Image')
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, default=None, related_name='imgs')

    def __str__(self):
        return str(self.project.title)


class Comment(models.Model):
    content = models.TextField(max_length=3000, blank=False)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(f'comment by {self.user.user.username} on {self.project.title} project.')


class ProjectReport(models.Model):
    content = models.TextField(max_length=3000)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)


class CommentReport(models.Model):
    comment = models.ForeignKey("Comment", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)


class Donation(models.Model):
    amount = models.IntegerField()
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Rate(models.Model):
    value = models.IntegerField(default=1,
                                validators=[
                                    MaxValueValidator(100),
                                    MinValueValidator(1)
                                ])
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    user = models.ForeignKey("users.Profile", on_delete=models.CASCADE)

#
# class Data(models.Model):
#     title = models.CharField(max_length=100)
#     tags = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.first_name

crowdFunding/projects/forms.py
from django import forms
from django.utils import timezone
from .models import Project, ProjectPicture
from django.forms import ModelForm


class ProjectsForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'details', 'target',
                  'start_date', 'end_date', 'category', 'tags']

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if end_date <= start_date:
            msg = u"End date should be greater than start date."
            self._errors["end_date"] = self.error_class([msg])


class ImageForm(forms.ModelForm):
    #image = forms.ImageField(label='Image')
    class Meta:
        model = ProjectPicture
        fields = ['img_url', ]

crowdFunding/projects/views.py
from .models import *
import json
import re
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .forms import ProjectsForm, ImageForm
from django.http.response import HttpResponse, JsonResponse,HttpResponseForbidden
from users.models import Profile
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib import messages
from django.db.models import Q, Avg, Sum
# Create your views here.
from taggit.models import Tag
from decimal import Decimal, ROUND_HALF_UP
from django.template.loader import render_to_string
from datetime import datetime


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def showProject(request, id):
    item = Project.objects.get(id=id)
    pPics = ProjectPicture.objects.all().filter(project_id=id)
    relatedProjects = Project.objects.all().filter(category_id=item.category)
    rate = item.rate_set.all().aggregate(Avg("value"))["value__avg"]
    rate = rate if rate else 0
    rate = Decimal(rate).quantize(0, ROUND_HALF_UP)
    today = datetime.now()
    start_date = item.start_date
    end_date = item.end_date
    myFormat = "%Y-%m-%d %H:%M:%S"
    today = today.strftime(myFormat)
    today = datetime.strptime(today, "%Y-%m-%d %H:%M:%S")
    start_date = start_date.strftime(myFormat)
    start_date = datetime.strptime(start_date, "%Y-%m-%d %H:%M:%S")
    end_date = end_date.strftime(myFormat)
    end_date = datetime.strptime(end_date, "%Y-%m-%d %H:%M:%S")
    donate = item.donation_set.all().aggregate(Sum("amount"))
    context = {'pData': item,
               'pPics': pPics,
               'rate': rate,
               'today': today,
               'start_date': start_date,
               'end_date': end_date,
               'relatedProjs': relatedProjects,
               'donations_amount': donate["amount__sum"] if donate["amount__sum"] else 0}

    if request.user:
        user_rate = item.rate_set.filter(
            user_id=request.user.profile.id).first()
        if user_rate:
            context["user_rate"] = user_rate.value
    return render(request, "projects/viewProject.html", context)


def showCategoryProjects(request, id):
    category = Category.objects.get(id=id)
    context = {'catName': category}
    return render(request, "projects/viewCategory.html", context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required
def create(request):

    ImageFormSet = modelformset_factory(
        ProjectPicture, form=ImageForm, min_num=1, extra=3)

    if request.method == 'POST':
        form = ProjectsForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=ProjectPicture.objects.none())

        if form.is_valid() and formset.is_valid():
            new_form = form.save(commit=False)
            new_form.user = Profile.objects.get(user=request.user)
            new_form.save()
            form.save_m2m()
            for form in formset.cleaned_data:
                # this helps to not crash if the user
                # do not upload all the photos
                if form:
                    image = form['img_url']
                    photo = ProjectPicture(project=new_form, img_url=image)
                    photo.save()
            return redirect(f'/projects/projectDetails/{new_form.id}')
        context = {
            'form': form,
            'formset': formset,
        }
        return render(request, 'projects/create.html', context)
    else:

        form = ProjectsForm()
        formset = ImageFormSet(queryset=ProjectPicture.objects.none())
        context = {
            'form': form,
            'formset': formset,
        }
    return render(request, 'projects/create.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def create_comment(request, id):
    if request.method == 'POST':
        if request.POST['content']:
            comment = Comment()
            comment.content = request.POST['content']
            comment.project_id = id
            comment.user = request.user.profile
            comment.save()
        return redirect(f'/projects/projectDetails/{id}')

def list_categories(request):
    categories = Category.objects.all()
    return {
        'categs': categories
    }


def home(request):
    projectRates = Rate.objects.all().values('project').annotate(
        Avg('value')).order_by('-value__avg')[:5]
    print(projectRates)

    hRatedProjects = []
    for p in projectRates:
        print(p.get('project'))
        hRatedProjects.extend(
            list(Project.objects.filter(id=p.get('project'))))
        print(hRatedProjects)

    # lFiveList = Project.objects.extra(order_by=['-created_at'])
    lFiveList = Project.objects.order_by('-created_at')[:5]
    featuredList = Project.objects.all().filter(is_featured='True')
    context = {
        'latestFiveList': lFiveList,
        'fProject': featuredList,
        'hRProjects': hRatedProjects,
    }

    return render(request, 'projects/Home.html', context)

def show_tag(request, slug):
    tag = get_object_or_404(Tag, slug=slug)

    projects = Project.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'projects': projects,
    }
    return render(request, 'projects/tag.html', context)


def report_project(request, id):
    if request.method == 'POST':
        report_pro = ProjectReport.objects.create(
            content=request.POST['report'],
            project_id=id,
            user=request.user.profile
        )

        return redirect(f'/projects/projectDetails/{id}')


def report_comment(request, id):
    if request.method == 'POST':
        if len(list(CommentReport.objects.filter(comment_id=request.POST['comment_id'], user=request.user.profile))) == 0:
            report_com = CommentReport.objects.create(

                comment_id=request.POST['comment_id'],
                user=request.user.profile
            )
            messages.success(request, "Your report sent sccussefully, We will look for it as soon as possible")

        else:
            messages.error(request, 'You reported this comment before!')
        return redirect(f'/projects/projectDetails/{id}')


def search(request):
    if request.method == "GET":
        query = request.GET.get('searchBox')
        if query is not None:
            projects = Q(title__icontains=query)
            results =Project.objects.filter(projects).distinct()
            print(results)
            context = {
                'currentUserId' : request.user.id,
                'currentuserName' : request.user.username,
                'projectOwnerId' : results[0].user_id,
                'projectOwnerName' : results[0].user,
                'mainProject' : results[0],
                'Images': ProjectPicture.objects.filter(project_id=results[0].id)
            }
            relatedProjects = []
            for project in results[1:]:
                proj = {
                    'relatedProj': project,
                    'Images': ProjectPicture.objects.filter(project_id=project['id'])
                }
                relatedProjects.append(proj)
                # project_list.append(ImageForm.objects.filter(project_id=project['project_id']))
            context['related'] = relatedProjects
            return render(request, 'projects/search.html', context)
            # return redirect(f'/projects/projectDetails.html/')
        else:
            return render(request, 'projects/search.html')
            # return redirect(f'/projects/projectDetails.html/')
    else:
        return render(request, 'projects/Home.html')
@login_required
def rate_project(request, id, value):
    if request.method == 'POST':
        user_id = request.user.profile.id
        print(f"{user_id} {id} {value}")

        Rate.objects.update_or_create(
            project_id=id,
            user_id=user_id,
            defaults={"value": value},
        )
        data = {
            'msg': "success"
        }
        return JsonResponse(data)


def donate(request, id):
    if request.method == 'POST':
        donate = Donation.objects.create(
            amount=request.POST['donate'],
            project_id=id,
            user=request.user.profile
        )
        return redirect(f'/projects/projectDetails/{id}')

def delete_project(request, id):
    # if request.method == 'POST':
    project = get_object_or_404(Project,id=id)
        # if (request.user.profile.id != project.id):
        #     # raise HttpResponseForbidden("Not allowed")
        #     return redirect(f"/users/profile/{project.id}")

    project.delete()
    # url = reverse("users/profile")
    return redirect(f'/users/profile/{request.user.profile.id}')
    # return redirect(url)

crowdFunding/projects/templates/projects/Home.html
{% extends 'projects/base.html' %}
{% load static %}

{% block head-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <link href="{% static 'css/home.css' %}" rel="stylesheet" media="screen">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}

    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" >
        {% for p in hRProjects %}
            {% if forloop.counter == 1 %}
                <div class="carousel-item slideCss active" >
                      <a href="{% url 'show_proj' p.id %}">
                      <img src="/static/{{p.imgs.all.first.img_url}}" class="d-block slideCss">
                      </a>
                      <div class="carousel-caption d-none d-md-block">
                      
                        <h5 class="sliderTitle" >{{p.title}}  </h5>
                        
                        <p class="sliderDesc"> {{p.details}}</p>
                        
                      </div>
                </div>
             {% else %}
                <div class="carousel-item slideCss" >
                <a href="{% url 'show_proj' p.id %}">
                      <img src="/static/{{p.imgs.all.first.img_url}}" class="d-block slideCss">
                      </a>
                      <div class="carousel-caption d-none d-md-block">
                    
                        <h5 class="sliderTitle">{{p.title}} </h5>
                        <p class="sliderDesc"> {{p.details}} </p>
                    
                      </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>

    <h1 class="subTitle"> Latest Projects</h1> 
    <hr>

    <div class="row">
        {% for p in latestFiveList %}
        {% if forloop.counter  != 2 and forloop.counter  <= 3 %}
            <div class="col-md-3 latestproject">
                <div class="card cardDes">
                     <a href="{% url 'show_proj' p.id %}">
                    <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg"> </a>
                    <div class="card-body">
                      <h5 class="card-title">{{ p.title }}</h5>
                      <p class="card-text desc">{{p.details }}</p>
                    </div>
                </div>
            </div>
        {% elif forloop.counter == 2 %}
            <div class="col-md-6 latestproject">
                <div class="card cardDes">
                 <a href="{% url 'show_proj' p.id %}">
                    <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg"> </a>
                    <div class="card-body">
                      <h5 class="card-title">{{p.title }}</h5>
                      <p class="card-text desc">{{p.details }}</p>
                    </div>
                </div>
            </div>
            {% elif forloop.counter > 3 %}
            <div class="col-md-6 latestproject">
                <div class="card cardDes">
                     <a href="{% url 'show_proj' p.id %}">
                    <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg"> </a>
                    <div class="card-body">
                      <h5 class="card-title">{{p.title }}</h5>
                      <p class="card-text desc">{{p.details }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>

    <h1 class="subTitle"> Featured Projects</h1> 
    <hr>

    <div class="row">
        {% for p in fProject %}
            <div class="fproject">
                <div class="card cardDes">
                     <a href="{% url 'show_proj' p.id %}">
                    <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg"> </a>
                    <div class="card-body">
                      <h5 class="card-title">{{p.title }}</h5>
                      <p class="card-text desc">{{p.details }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>  

    <h1 class="subTitle"> Our Categories </h1> 
    <hr>

    <div class="row">
        {% for c in categs %}
            <div class="categs">
                <a href="{% url 'show_cate' c.id %}">
                <img src="/static/{{ c.cat_icon }}" class="card-img-top"> </a>
                <h5 class="card-title" style="text-align: center;">{{c.name }}</h5>
            </div>
        {% endfor %}
    </div>
{% endblock %}

crowdFunding/projects/templates/projects/base.html
{% load static %}

<html lang="en">

<head>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'users/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'users/css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'users/css/style.min.css' %}" rel="stylesheet">

    <meta charset="UTF-8">
    <title> {% block title %} Home {% endblock title %}</title>

    {% block head-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/nav.css' %}">
    {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg sticky-top">
        <span class="navbar-brand" href="">CrowdFunding</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'createCategory' %}">Create Category <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for c in categs %}
                        <a class="dropdown-item" href="{% url 'show_cate' c.id %}">{{c.name}}</a>
                        {% endfor %}
                    </div>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'create_project' %}">New Project <span class="sr-only">(current)</span></a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class=" nav-item nav-link" href="{% url 'logout' %}">logout<span
                            class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign up<span
                            class="sr-only">(current)</span></a>

                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:profile' user.id  %}">{{user.username}} <span
                            class="sr-only">(current)</span></a>
                </li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0" id="searchForm"  method = "GET" action="{%url 'search'%}">
                {% csrf_token %}
                <input name='searchBox' class="form-control mr-sm-2" type="search" placeholder="Search"
                    aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="submit"  action =''>Search</button>
            </form>

        </div>
    </nav>


    <!-- This is where you'll put your page content. Leave it blank for now. -->
    <div class="container">
        {% block content %}Nothing Here{% endblock %}
    </div>



    <footer class="mainfooter" role="contentinfo">
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 copy">
                                <p class="text-center"><a href="https://github.com/aAbdelnaby88/Crowd-Funding">
                                        &copy; Copyright 2020 - ITIan's .All rights reserved.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'users/js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'users/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'users/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'users/js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'projects/js/searchAjax.js' %}"></script>


</body>

</html>

crowdFunding/projects/templates/projects/create.html
{% extends 'projects/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput.css' %}">

<form class="create_s" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        {{ form.title|as_crispy_field }}
        {{ form.details|as_crispy_field }}
        {{ form.target|as_crispy_field }}
        {{ form.start_date|as_crispy_field }}
        {{ form.end_date|as_crispy_field }}
        {{ form.category|as_crispy_field }}
        <div class="form-group">
          <label>Tags</label>
          <input type="text" data-role="tagsinput" class="form-control" name="tags">
        </div>
      </div>
      <div class="col-8">
        {{ formset|crispy }}
      </div>
    </div>
  </div>
  <br>
  <button type="submit" class="boy btn btn-success ">Create Project</button>
</form>
{% block js %}
<script type="text/javascript" src="{% static 'js/bootstrap-tagsinput.js' %}"></script>
{% endblock %}


{% endblock %}

crowdFunding/projects/templates/projects/viewCategory.html
{% extends 'projects/base.html' %}
{% load static %}

{% block head-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <link href="{% static 'css/viewCat.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block title %} 
    {{ catName.name }}
{% endblock %}

{% block content %}
    <div class="row">
        {% for p in catName.project_set.all %}
            <div class="col-md-3 mt-4">
                <div class="card cardDes">
                    <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg">
                    <div class="card-body">
                      <h5 class="card-title">{{p.title }}</h5>
                      <p class="card-text desc">{{p.details }}</p>
                      <a href="{% url 'show_proj' p.id %}" class="btn btn-primary"> Show Details </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}