crowdFunding/crowdFunding/urls.py
from django.urls import path , include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings
from projects import urls, views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/' , include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('projects/',include('projects.urls')),
    path('search/',views.search),
    path('',views.home, name = 'home'),
    path('categories/', include('categories.urls')),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crowdFunding/users/urls.py
# from django.conf.urls import url
from django.urls import path , include , re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('profile/<int:uid>', views.userProfile , name='profile'),

    path('edit/<int:uid>', views.editProfile , name='edit'),
    path('delete/<int:uid>', views.deleteuser, name="delete"),
    path('signup',views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view\
        (template_name='users/logout.html'), name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    
    # path('login/', views.custom_login),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate_account, name='activate')

]

crowdFunding/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from PIL import Image
from django_countries.fields import CountryField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE , verbose_name=("User Name"))
    email_confirmation = models.BooleanField(default=False , verbose_name=("Email"))
    phone_validation = RegexValidator(regex=r'^01[5|1|2|0][0-9]{8}$',
                                 message=" Please ,, Entered the Phone number in the format: '010|212|134|156'.")
    phone = models.CharField(max_length=11, null=True, blank=True , verbose_name=("Phone"))
    facebook =  models.URLField(null=True, blank=True , verbose_name=("FaceBook"))
    country = CountryField()
    birth_date = models.DateField(null=True, blank=True, verbose_name=("BirthDate"))
    user_image = models.ImageField(upload_to='images/users', default='images/users/R.jpg')

    def __str__(self):
        
        return f'{self.user.username}'
        img = Image.open(self.user_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.user_image.path)

     



    def create_profile(sender, **kwargs):
        if kwargs['created']:
            user_profile = Profile.objects.create(user=kwargs['instance'])


    post_save.connect(create_profile, sender=User)

crowdFunding/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django.forms import ModelForm

class SignUpForm(UserCreationForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
        return email
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Inform a valid email address.')
    birth_date = forms.DateField(required=False,help_text='Optional.')
    phone = forms.CharField(max_length=11,required=False, help_text='Optional.')
    user_image = forms.ImageField(label = "upload your image",required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2','user_image')
        unique_together = ('email',)

class UserUpdateForm(forms.ModelForm):
   

    class Meta:
         model = User
         fields = ['first_name', 'last_name']

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
         model = Profile
         fields = ['user_image', 'birth_date', 'country', 'facebook', 'phone']


# class UserFormPassword(ModelForm):
#     class Meta:
#         model = User
#         fields = ['password',]

class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = User
        fields = []   #Form has only submit button.  Empty "fields" list still necessary, though.

crowdFunding/users/views.py
from email import message
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm, UserDeleteForm
from django.contrib.auth import login, authenticate, logout ,get_user_model
from django.db.models import Avg, Sum
from django.contrib.auth.decorators import login_required
from users.models import Profile
from projects.models import Project, Category, Donation, Rate
from decimal import Decimal, ROUND_HALF_UP
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes , force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage

# Create your views here.

# def custom_login(request,**kwargs):
#     if request.user.is_authenticated:
#         return redirect('/')
#     else:
#         return login(request,**kwargs)
def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('login')
    else:
        messages.error(request, 'Activation link is invalid!')
    
    return redirect('/')


def activateEmail(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('users/activate_account.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
            received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending confirmation email to {to_email}, check if you typed it correctly.')

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('/')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = SignUpForm()

    return render(
        request=request,
        template_name="registration/signup.html",
        context={"form": form}
        )



@login_required
def userProfile(request, uid):
    user2 = get_object_or_404(User, id=uid)
    categories = Category.objects.all()
    projects = Project.objects.all().filter(user_id=uid)
    for p in projects:

        donation_sum = p.donation_set.all().aggregate(Sum("amount"))['amount__sum']
        p.donation_sum = donation_sum if donation_sum else 0
        p.delete_flag = True if p.donation_sum <= p.target * 0.25 else False

    context = {
        'userprofile': user2,
        'userProject': projects,
        'categories': categories,
        'donations': Donation.objects.all().filter(user_id=uid),
        'latestFiveList': Project.objects.extra(order_by=['created_at'])
    }
    return render(request, "users/profile.html", context)


@login_required
def editProfile(request, uid):
    if request.user.profile.id != uid:
        raise Http404("Not Found")
    user2 = get_object_or_404(User, id=uid)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=user2)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=user2.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile', uid=uid)

    else:
        u_form = UserUpdateForm(instance=user2)
        p_form = ProfileUpdateForm(instance=user2.profile)
    context = {
        "userprofile": user2,
        # "categories": categories,
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, "users/edit_profile.html", context)


@login_required
def deleteuser(request, uid):
    user2 = get_object_or_404(User, id=uid)
    if request.method == 'POST':
        delete_form = UserDeleteForm(request.POST, instance=user2)
        user2.delete()
        messages.info(request, 'Your account has been deleted.')
        return redirect('/')
    else:
        delete_form = UserDeleteForm(instance=user2)

    context = {
        'delete_form': delete_form
    }

    return render(request, 'users/delete_account.html', context)

crowdFunding/users/templates/users/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

crowdFunding/users/templates/users/base.html
{% load static %}

<html lang="en">

<head>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'users/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'users/css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'users/css/style.min.css' %}" rel="stylesheet">

    <meta charset="UTF-8">
    <title> {% block title %} Home {% endblock title %}</title>

    {% block head-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/style.css' %}">
    {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg sticky-top">
        <span class="navbar-brand" href="{% url 'home' %}">CrowdFunding</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'createCategory' %}">Create Category <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for c in categs %}
                        <a class="dropdown-item" href="{% url 'show_cate' c.id %}">{{c.name}}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'create_project' %}">New Project <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}

                <li class="nav-item active">
                    <a class=" nav-item nav-link" href="{% url 'users:logout' %}">logout<span
                            class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign up<span
                            class="sr-only">(current)</span></a>

                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:profile' user.id  %}">{{user.username}} <span
                            class="sr-only">(current)</span></a>
                </li>
                {% endif %}
            </ul>
            {% comment %}
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% endcomment %}
        </div>
    </nav>


    <!-- This is where you'll put your page content. Leave it blank for now. -->
    <div class="container">
        {% block content %}Nothing Here{% endblock %}
    </div>



    <footer class="mainfooter" role="contentinfo">
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 copy">
                                <p class="text-center"><a href="https://github.com/aAbdelnaby88/Crowd-Funding">
                                        &copy; Copyright 2020 - ITIan's .All rights reserved.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'users/js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'users/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'users/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'users/js/mdb.min.js' %}"></script>

</body>

</html>

crowdFunding/users/templates/users/delete_account.html
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete User Account</legend>
            <p>Are you sure you want to delete your account?  This will permanently delete your
               profile and any content you have generated.</p>
            {{ form }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-danger" type="submit">Delete Account</button>

    </div>
</form>

crowdFunding/users/templates/users/edit_profile.html
{% extends 'users/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<main role="main">
 <div class="row align-items-center">
     <div class="col-md-2"></div>
     <div class="col-md-8 m-4">
           <form method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               <fieldset class="form-group">
                   <legend class="border-bottom mb-4">Update Info</legend>
                   {{ u_form|crispy }}
                   {{ p_form|crispy }}
               </fieldset>
               <div class="form-group">

                   <button class="btn btn-info" type="submit">Update</button>
                   <a href = "{% url 'users:delete' userprofile.id  %}" class="btn btn-danger">Delete Profile</a>
               </div>
           </form>
     </div>
     <div class="col-md-2"></div>
 </div>
</main>
{% endblock %}

crowdFunding/users/templates/users/logout.html
{% extends "users/base.html" %}

{% block content %}
  <p>Logged out!</p>  
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

crowdFunding/users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load countries %}
{% get_country 'BR' as country %}
{% load crispy_forms_tags %}

{% block content %}
<main role="main" class="container mt-4">
  <div class="row">
    <div class="col-md-8">

      <div class="content-section">
        <div class="media" >
          {% if userprofile.profile.user_image %}
          <img src="{{ userprofile.profile.user_image.url }}" width="150" height="150"
            class="rounded-circle account-img ml-4">
          {% endif %}

          <div class="media-body m-1 mt-4">
            <h4 class="account-heading">{{userprofile.first_name}} {{userprofile.last_name}}</h4>
            <p class="text-secondary">
              {{userprofile.email}}
            </p>
          </div>
        </div>
        <!-- FORM HERE -->

        <div class="container">

          <!--  projects   -->
          <div class="card-deck">
            {% for p in userProject %}

            <div class="col-md-6 mt-4">
              <div class="card cardDes">
                <a href="{% url 'show_proj' p.id %}">
                  <img src="/static/{{ p.imgs.all.first.img_url }}" class="card-img-top projImg"> </a>
                <div class="card-body">
                  <h5 class="card-title mb-1">{{p.title }}</h5>
                  <p class="card-text mb-1">Category: <a href="{% url 'show_cate' p.id %}">{{ p.category }}</a><br />

                    <p class="card-text desc"> Details: {{p.details }}</p>
                    {% if p.delete_flag %}
                    <form action="{% url 'delete_project' p.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" style="margin-left: 0;" class="btn btn-danger" >cancel project</button>
                    </form>
                    {% endif %}
                </div>
              </div>
            </div>

            {% endfor %}
          </div>
          <div>
            <h2 class="h1 mb-2 mt-4 text-center text-muted" id="donations"> Donations </h2>
          </div>

          <div class="card-deck ">
            {% for p in donations %}
            <div class="col-md-6 mt-4">
              <div class="media shadow mb-2 bg-white rounded" style="height:80px;">
                <div class="row ">
                  <div class="col-sm-4">
                    <a href="{% url 'show_proj' p.id %}">
                      <img src="/static/{{ p.project.imgs.all.first.img_url }}" alt="John Doe" class="mr-3"
                        style="width:70px; height: 80px;">
                    </a>
                  </div>
                  <div class="col-sm-8">
                    <div class="media-body mr-3 mt-2">
                      <h6>{{ p.project.title }}</h6>
                      Quantity: {{ p.amount }}$<br />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div>
          <h2 class="h1 mb-4 mt-4 text-center text-muted" id="about"> Profile Info</h2>
        </div>
        <div class="card">

          <div class="card-body">

            <p class="card-text">


              <ul class="list-unstyled">
                <li class="py-3 pl-2 border-bottom bg-light">

                  <span class="text-primary h3 mr-3"> <i class="fas fa-user "></i> User Name :</span>
                  <span class="h4 text-muted">{{userprofile.first_name}} {{userprofile.last_name}}</span>
                </li>

                <li class="py-3 pl-2 border-bottom bg-light">
                  <span class="text-success h3 mr-3"> <i class="fas fa-envelope"></i> Email :</span>
                  <span class="h4 text-muted">{{ userprofile.email }}</span>
                </li>
                <li class="py-3 pl-2 border-bottom bg-light">
                  <span class="text-info h3 mr-3"> <i class="fab fa-facebook-square"></i> FaceBook :</span>
                  <span class="h4 text-muted">{{userprofile.profile.facebook|default_if_none:'-------'}}</span>
                </li>
                <li class="py-3 pl-2 border-bottom bg-light">
                  <span class="text-warning h3 mr-3"> <i class="fas fa-city"></i> country :</span>
                  <span class="h4 text-muted">{{userprofile.profile.country.name|default_if_none:'-------'}}</span>
                </li>
                <li class="py-3 pl-2 border-bottom bg-light">
                  <span class="text-danger h3 mr-3"> <i class="fas fa-birthday-cake"></i> Birth Date :</span>
                  <span class="h4 text-muted">{{userprofile.profile.birth_date|default_if_none:'-------'}}</span>
                </li>

                <li class="py-3 pl-2 border-bottom bg-light">
                  <span class="text-secondary h3 mr-3"> <i class="fas fa-phone"></i> Phone :</span>
                  <span class="h4 text-muted">{{userprofile.profile.phone|default_if_none:'-------'}}</span>
                </li>

              </ul>

            </p>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Options</h3>
        <p class='text-muted'>
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">
              <div class="dropdown show">
                <a class="dropdown-toggle" data-hover="dropdown" href="#" role="button" id="dropdownMenuLink"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Latest Projects
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  {% for p in latestFiveList %}
                  {% if forloop.counter >= 1 %}
                  <a class="dropdown-item" href="{% url 'show_proj' p.id %}">{{ p.title }}</a>
                  {% endif %}
                  {% endfor %}

                </div>
              </div>


            </li>
            <li class="list-group-item list-group-item-light"><a class="sidebar" href="#donations">Donations</a></li>
            <li class="list-group-item list-group-item-light"><a class="sidebar" href="#about">About</a></li>
            {% if user.id == userprofile.id %}
            <li class="list-group-item list-group-item-light"><a class="sidebar"
                href="{% url 'users:edit' userprofile.id %}">Edit Profile</a></li>
            {% endif %}
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
{% endblock %}